[[redirects]]
  from = "/nuevas-ofertas-stadia-pro-50-descuento-bordelands-3-tomb-raider"
  to = "/nuevas-ofertas-stadia-pro-50-descuento-borderlands-3-tomb-raider"
  status = 301
  force = false

[[redirects]]
  from = "/juegos-mmorpg-stadia-proyecto-quimera-google"
  to = "/juegos-mmorpg-stadia-proyecto-chimera-google"
  status = 301
  force = false

[[redirects]]
  from = "/juego-basado-warhammer-es-posible-llegue-stadia"
  to = "/juego-warhammer-age-of-sigmar-es-posible-llegue-stadia"
  status = 301
  force = false

[[redirects]]
  from = "/pga-tour-2k21-2k-stadia-21-mayo"
  to = "/pga-tour-2k21-2k-llegara-stadia"
  status = 301
  force = false

[[redirects]]
  from = "/assasins-creed-valhalla-stadia-finales-ano"
  to = "/assassins-creed-valhalla-stadia-finales-ano"
  status = 301
  force = false

[[redirects]]
  from = "/assasins-creed-odyssey"
  to = "/assassins-creed-odyssey"
  status = 301
  force = false

[[redirects]]
  from = "/gana-saldo-gratis-stadia-google-rewards"
  to = "/gana-saldo-juegos-gratis-stadia-google-rewards"
  status = 301
  force = false

[[redirects]]
  from = "/por-fin-stadia-incluye-controles-tactiles-movil"
  to = "/stadia-controles-tactiles-movil"
  status = 301
  force = false

[[redirects]]
  from = "/juegos_gratuitos_stadia_pro_de_julio_crayta_monster_boy_and_the_cursed_kingdom_steamworld_dig_y_west_of_loathing"
  to = "/juegos-gratuitos-stadia-pro-de-julio-crayta-monster-boy-and-the-cursed-kingdom-steamworld-dig-y-west-of-loathing"
  status = 301
  force = false

  